micronaut:
  application:
    name: ${APPLICATION_NAME:itemservice}
  server:
    port: ${APPLICATION_PORT:8081}
  io:
    watch:
      paths: 'src/main'
      restart: true

datasources:
  default:
    url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
    username: ${JDBC_USER:sa}
    password: ${JDBC_PASSWORD:""}
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}

jpa:
  default:
    packages-to-scan:
      - 'com.item.entity'
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        show_sql: true

flyway:
  datasources:
    default:
      locations: classpath:db/migrations